### ISSUE TITLE
Update the team listing

### ISSUE THREAD

**Issue by powersj** [canonical-web-and-design/cloud-init.io#104]
## Summary

We need to add and update the folks listed on the team:

- Joshua Powers
    - Josh is the Engineering Manager of Ubuntu Server at Canonical.
- Ryan Harper
    - Ryan is one of the primary maintainers of cloud-init at Canonical.
- Chad Smith
    - Chad is one of the primary maintainers of cloud-init at Canonical.
- Dan Watkins
    - Dan is one of the primary maintainers of cloud-init at Canonical.
- Paride Legovini
   - Paride is QA engineer on Ubuntu Server at Canonical.
- Scott Moser
    - Scott is the primary author and active maintainer of cloud-init, who works at Cisco.
- Joshua Harlow
    - Joshua is an active maintainer of cloud-init, who works at PlusAI. 

## Process

Go to the site, scroll down and realize 4 people are missing.

## Current and expected result

Only two older contributors, who should still be listed on the site, are there.

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
@powersj can we get photos of you all?

**Comment by kwm14** [comment]
@pmahnke we could get them from the Directory?

Did you want me to add the new members as I'm currently upgrading the site to test 2.0.0-alpha?

**Comment by kwm14** [comment]
@powersj Something like this? I used headshots from the directory. Let me know if you want them updated to something else 😄

<img width="1440" alt="Screenshot 2019-05-22 at 16 58 31" src="https://user-images.githubusercontent.com/17748020/58189764-00726d00-7cb3-11e9-8fe7-cc28e86f2f39.png">

**Comment by powersj** [comment]
This is awesome :)

* Paride: change "is QA engineer on" to "is the QA engineer of"
* Ryan/Chad/Dan change "one of the" to "a"

**Comment by kwm14** [comment]
Updated copy 👍 

I will push this update into the test [PR](https://github.com/canonical-web-and-design/cloud-init.io/pull/103) and release when we upgrade in v2.0.0 in the coming weeks.

<img width="1440" alt="Screenshot 2019-05-23 at 09 22 30" src="https://user-images.githubusercontent.com/17748020/58237165-5b03db80-7d3c-11e9-9cfe-53f00734e9ee.png">

**Comment by powersj** [comment]
Works for me!
